include:
  - template: Terraform/Base.latest.gitlab-ci.yml

stages:
  - init
  - validate
  - build
  - deploy
  - destroy

init:
  stage: init
  script:
    - terraform init

validate:
  stage: validate
  script:
    - terraform validate
  dependencies:
    - init

build:
  stage: build
  script:
    - terraform plan
  artifacts:
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  dependencies:
  - init

deploy:
  stage: deploy
  script:
    - terraform apply
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $TF_AUTO_DEPLOY == "true"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy
  resource_group: ${TF_STATE_NAME}
  when: manual