include:
  - template: Terraform/Base.latest.gitlab-ci.yml

stages:
  - init
  - validate
  - build
  - deploy
  - destroy

init:
  extends: .terraform:init

validate:
  extends: .terraform:validate

build:
  extends: .terraform:build
  artifacts:
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

deploy:
  extends: .terraform:deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $TF_AUTO_DEPLOY == "true"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

destroy:
  extends: .terraform:destroy
    when: manual